# ----------------------------------------
# Created on: Tue Sep 19 11:00:43 2023
# Auto generated by Pango
# ----------------------------------------

vsim  -novopt  -L work tb_mdio_rw_test
add wave *
view wave
view structure
view signals

run 1000ns

# ----------------------------------------
