# ----------------------------------------
# Created on: Sun Oct  8 15:08:27 2023
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "D:/modeltech64_2020.4/pango/PDS22SP4/usim"
vmap  adc "D:/modeltech64_2020.4/pango/PDS22SP4/adc"
vmap  ddrc "D:/modeltech64_2020.4/pango/PDS22SP4/ddrc"
vmap  ddrphy "D:/modeltech64_2020.4/pango/PDS22SP4/ddrphy"
vmap  hsst_e2 "D:/modeltech64_2020.4/pango/PDS22SP4/hsst_e2"
vmap  iolhr_dft "D:/modeltech64_2020.4/pango/PDS22SP4/iolhr_dft"
vmap  ipal_e1 "D:/modeltech64_2020.4/pango/PDS22SP4/ipal_e1"
vmap  pciegen2 "D:/modeltech64_2020.4/pango/PDS22SP4/pciegen2"
vlog -work work   \
"E:/Document/FPGA/PGL/PGL25G/Finalized/lcd_rgb_colorbar/rtl/clk_div.v" \
"E:/Document/FPGA/PGL/PGL25G/Finalized/lcd_rgb_colorbar/rtl/lcd_display.v" \
"E:/Document/FPGA/PGL/PGL25G/Finalized/lcd_rgb_colorbar/rtl/lcd_driver.v" \
"E:/Document/FPGA/PGL/PGL25G/Finalized/lcd_rgb_colorbar/rtl/lcd_rgb_colorbar.v" \
"E:/Document/FPGA/PGL/PGL25G/Finalized/lcd_rgb_colorbar/rtl/rd_id.v" \
"E:/Document/FPGA/PGL/PGL25G/Finalized/lcd_rgb_colorbar/sim/tb_lcd_rgb_colorbar.v" 

# ----------------------------------------
