#Generated by Fabric Compiler ( version 2022.2-SP4.2 <build 132111> ) at Tue Sep 19 14:03:43 2023

add_design "D:/Desktop/8_edge_test/rtl/edge_test.v"
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module edge_test
add_simulation "D:/Desktop/8_edge_test/sim/tb_edge_test.v"
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module edge_test
