# ----------------------------------------
# Created on: Tue Sep 19 17:03:14 2023
# Auto generated by Pango
# ----------------------------------------

vsim  -novopt  -L work tb_not_gate
add wave *
view wave
view structure
view signals

run 1000ns

# ----------------------------------------
