# ----------------------------------------
# Created on: Sat Sep 23 14:24:46 2023
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "D:/PANGO/prjx/usim"
vmap  adc "D:/PANGO/prjx/adc"
vmap  ddrc "D:/PANGO/prjx/ddrc"
vmap  ddrphy "D:/PANGO/prjx/ddrphy"
vmap  hsst_e2 "D:/PANGO/prjx/hsst_e2"
vmap  iolhr_dft "D:/PANGO/prjx/iolhr_dft"
vmap  ipal_e1 "D:/PANGO/prjx/ipal_e1"
vmap  pciegen2 "D:/PANGO/prjx/pciegen2"
vlog -work work   \
"D:/Desktop/10_flow_led/rtl/flow_led.v" \
"D:/Desktop/10_flow_led/sim/tb/tb_flow_led.v" 

# ----------------------------------------
