#Generated by Fabric Compiler ( version 2021.4-SP1.2 <build 96435> ) at Thu Sep  1 16:52:11 2022

add_design "E:/Verilog/32_ov5640_hdmi/rtl/ov5640_hdmi.v"
add_design E:/Verilog/32_ov5640_hdmi/prj/ipcore/pll_clk/pll_clk.idf
add_design "E:/Verilog/32_ov5640_hdmi/rtl/ov5640_dri.v"
add_design "E:/Verilog/32_ov5640_hdmi/rtl/i2c_ov5640_rgb565_cfg.v"
add_design "E:/Verilog/32_ov5640_hdmi/rtl/i2c_dri.v"
add_design "E:/Verilog/32_ov5640_hdmi/rtl/cmos_capture_data.v"
add_design "E:/Verilog/32_ov5640_hdmi/rtl/video_driver.v"
add_design "E:/Verilog/32_ov5640_hdmi/rtl/dvi_transmitter_top.v"
add_design "E:/Verilog/32_ov5640_hdmi/prj/source/asyn_rst_syn.v"
remove_design -force -verilog "E:/Verilog/32_ov5640_hdmi/prj/source/asyn_rst_syn.v"
add_design "E:/Verilog/32_ov5640_hdmi/rtl/asyn_rst_syn.v"
add_design "E:/Verilog/32_ov5640_hdmi/rtl/dvi_encoder.v"
add_design "E:/Verilog/32_ov5640_hdmi/rtl/serializer_10_to_1.v"
add_design "E:/Verilog/32_ov5640_hdmi/rtl/ddr3_top.v"
add_design "E:/Verilog/32_ov5640_hdmi/rtl/rw_ctrl_128bit.v"
add_design E:/Verilog/32_ov5640_hdmi/prj/ipcore/ddr3_ip/ddr3_ip.idf
add_design "E:/Verilog/32_ov5640_hdmi/rtl/ddr3_fifo_ctrl.v"
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
add_design E:/Verilog/32_ov5640_hdmi/prj/ipcore/rd_fifo/rd_fifo.idf
add_design E:/Verilog/32_ov5640_hdmi/prj/ipcore/wr_fifo/wr_fifo.idf
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
add_constraint "E:/Verilog/32_ov5640_hdmi/prj/ov5640_hdmi.fdc"
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
add_design "E:/Verilog/32_ov5640_hdmi/rtl/hdmi_top.v"
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
add_design "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/ov5640_dri/cmos_capture_data.v"
add_design "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/ov5640_dri/i2c_dri.v"
add_design "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/ov5640_dri/i2c_ov5640_rgb565_cfg.v"
add_design "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/ov5640_dri/ov5640_dri.v"
add_design "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/hdmi_top/asyn_rst_syn.v"
add_design "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/hdmi_top/dvi_encoder.v"
add_design "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/hdmi_top/dvi_transmitter_top.v"
add_design "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/hdmi_top/hdmi_top.v"
add_design "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/hdmi_top/serializer_10_to_1.v"
add_design "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/hdmi_top/video_driver.v"
add_design "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/ddr3_top/ddr3_fifo_ctrl.v"
add_design "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/ddr3_top/ddr3_top.v"
add_design "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/ddr3_top/rw_ctrl_128bit.v"
add_design "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/ddr3_ctrl_top/aq_axi_master.v"
add_design "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/ddr3_ctrl_top/ctrl_fifo.v"
add_design "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/ddr3_ctrl_top/ddr3_ctrl_top.v"
add_design "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/ddr3_ctrl_top/ddr3_rw_ctrl.v"
remove_design -verilog "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/i2c_ov5640_rgb565_cfg.v"
remove_design -verilog "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/ov5640_dri.v"
remove_design -verilog "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/i2c_dri.v"
remove_design -verilog "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/cmos_capture_data.v"
remove_design -verilog "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/video_driver.v"
remove_design -verilog "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/dvi_transmitter_top.v"
remove_design -verilog "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/asyn_rst_syn.v"
remove_design -verilog "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/dvi_encoder.v"
remove_design -verilog "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/serializer_10_to_1.v"
remove_design -verilog "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/ddr3_top.v"
remove_design -verilog "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/rw_ctrl_128bit.v"
remove_design -verilog "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/ddr3_fifo_ctrl.v"
remove_design -verilog "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/hdmi_top.v"
remove_design -force C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/prj/ipcore/ddr3_ip/ddr3_ip.idf
add_design C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/prj/ipcore/ddr3_ip/ddr3_ip.idf
remove_design -force -verilog "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/ddr3_top/ddr3_top.v"
remove_design -force -verilog "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/ddr3_top/ddr3_fifo_ctrl.v"
remove_design -force C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/prj/ipcore/pll_clk/pll_clk.idf
add_design C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/prj/ipcore/pll_clk/pll_clk.idf
remove_design -force -verilog "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/ddr3_top/rw_ctrl_128bit.v"
remove_design -force -verilog "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/rtl/ddr3_top/rw_ctrl_128bit.v"
add_design "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/prj/ipcore/pll_clk/pll_clk.idf"
remove_constraint -force -logic -fdc "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/prj/ov5640_hdmi.fdc"
add_constraint "C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_hdmi/prj/source/ov5640_hdmi_pin.fdc"
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
