#Generated by Fabric Compiler ( version 2022.2-SP4.2 <build 132111> ) at Mon Sep 18 13:37:17 2023

add_design "D:/Desktop/2_gate/3_not_gate/rtl/not_gate.v"
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module not_gate
add_constraint "D:/Desktop/2_gate/3_not_gate/prj/not_gate.fdc"
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
add_simulation "D:/Desktop/2_gate/3_not_gate/sim/tb_not_gate.v"
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module not_gate
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module not_gate
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module not_gate
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
