# ----------------------------------------
# Created on: Fri Sep 15 13:57:23 2023
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/usim"
vmap  adc "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/adc"
vmap  ddrc "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/ddrc"
vmap  ddrphy "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/ddrphy"
vmap  hsst_e2 "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/hsst_e2"
vmap  iolhr_dft "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/iolhr_dft"
vmap  ipal_e1 "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/ipal_e1"
vmap  pciegen2 "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/pciegen2"
vlog -work work   \
"E:/PDS/ip_pll/rtl/ip_pll.v" \
"E:/PDS/ip_pll/prj/ipcore/pll_clk/pll_clk.v" \
"E:/PDS/ip_pll/sim/tb/tb_ip_pll.v" 

# ----------------------------------------
