# ----------------------------------------
# Created on: Tue Sep 19 17:03:14 2023
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vlog -work work   \
"D:/Desktop/2_gate/3_not_gate/rtl/not_gate.v" \
"D:/Desktop/2_gate/3_not_gate/sim/tb_not_gate.v" 

# ----------------------------------------
