#Generated by Fabric Compiler ( version 2022.2-SP4.2 <build 132111> ) at Tue Sep 19 14:28:02 2023

add_design "D:/Desktop/9_even_div/rtl/divider_4.v"
add_simulation "D:/Desktop/9_even_div/sim/tb_divider_4.v"
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module divider_4
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module divider_4
