#Generated by Fabric Compiler ( version 2021.4-SP1.2 <build 96435> ) at Mon Jul 11 09:59:47 2022

add_design "J:/pds/eth_arp_test/rtl/arp_ctrl.v"
add_design "J:/pds/eth_arp_test/rtl/eth_arp_test.v"
add_design "J:/pds/eth_arp_test/rtl/arp/arp.v"
add_design "J:/pds/eth_arp_test/rtl/arp/arp_rx.v"
add_design "J:/pds/eth_arp_test/rtl/arp/arp_tx.v"
add_design "J:/pds/eth_arp_test/rtl/arp/crc32_d8.v"
add_design "J:/pds/eth_arp_test/rtl/reset_dly.v"
add_design "J:/pds/eth_arp_test/rtl/gmii_to_rgmii/gmii_to_rgmii.v"
add_design "J:/pds/eth_arp_test/rtl/gmii_to_rgmii/rgmii_rx.v"
add_design "J:/pds/eth_arp_test/rtl/gmii_to_rgmii/rgmii_tx.v"
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
add_design J:/pds/eth_arp_test/prj/ipcore/pll_clk/pll_clk.idf
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
add_constraint "J:/pds/eth_arp_test/prj/source/prj/eth_arp_test.fdc"
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
remove_design -force -verilog "J:/pds/eth_arp_test/rtl/eth_arp_test.v"
add_design "J:/pds/eth_arp_test/rtl/eth_arp_test.v"
remove_design -force -verilog "J:/pds/eth_arp_test/rtl/gmii_to_rgmii/gmii_to_rgmii.v"
remove_design -force -verilog "J:/pds/eth_arp_test/rtl/gmii_to_rgmii/rgmii_rx.v"
remove_design -force -verilog "J:/pds/eth_arp_test/rtl/gmii_to_rgmii/rgmii_tx.v"
add_design "J:/pds/eth_arp_test/rtl/util_gmii_to_rgmii.v"
remove_design -force -verilog "J:/pds/eth_arp_test/rtl/eth_arp_test.v"
add_design "J:/pds/eth_arp_test/rtl/eth_arp_test.v"
add_design J:/pds/eth_arp_test/prj/ipcore/pll_sft/pll_sft.idf
remove_design -force J:/pds/eth_arp_test/prj/ipcore/pll_clk/pll_clk.idf
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
remove_constraint -force -logic -fdc "J:/pds/eth_arp_test/prj/source/prj/eth_arp_test.fdc"
add_constraint "J:/pds/eth_arp_test/prj/eth_arp_test.fdc"
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
gen_netlist 
report_power 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
remove_design -force -verilog "J:/pds/eth_arp_test/rtl/util_gmii_to_rgmii.v"
add_design "J:/pds/eth_arp_test/rtl/util_gmii_to_rgmii.v"
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
add_design "J:/pds/bc/eth_arp_test/rtl/gmii_to_rgmii/gmii_to_rgmii.v"
add_design "J:/pds/bc/eth_arp_test/rtl/gmii_to_rgmii/rgmii_rx.v"
add_design "J:/pds/bc/eth_arp_test/rtl/gmii_to_rgmii/rgmii_tx.v"
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
remove_design -force -verilog "J:/pds/bc/eth_arp_test/rtl/util_gmii_to_rgmii.v"
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
add_design "J:/pds/bc/eth_arp_test/sim/tb/tb_arp.v"
remove_design -force -verilog "J:/pds/bc/eth_arp_test/sim/tb/tb_arp.v"
add_simulation "J:/pds/bc/eth_arp_test/sim/tb/tb_arp.v"
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
add_fic "E:/pds/bc/eth_arp_test/prj/synthesize/eth_arp_test_syn.fic"
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
remove_fic -force"E:/pds/bc/eth_arp_test/prj/synthesize/eth_arp_test_syn.fic"
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
add_fic "E:/pds/bc/eth_arp_test/prj/synthesize/eth_arp_test_syn.fic"
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
remove_fic -force"C:/Users/ch/Desktop/90/eth_arp_test/prj/synthesize/eth_arp_test_syn.fic"
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL22G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
add_fic "E:/ziguang_pro_yanzheng/43_eth_arp_test/prj/synthesize/eth_arp_test_syn.fic"
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
add_design E:/ziguang_pro_yanzheng/43_eth_arp_test/prj/ipcore/pll_250/pll_250.idf
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
dev_map 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
remove_fic -force"C:/Users/Admin/Desktop/50G/eth_arp_test/prj/synthesize/eth_arp_test_syn.fic"
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
remove_design -force C:/Users/Admin/Desktop/25G/2_eth_arp_test/prj/ipcore/pll_250/pll_250.idf
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module eth_arp_test
synthesize -dir {E:/PDS_2022.1/Pango/PDS_2022.1/syn/bin/synplify_pro.exe} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream -unused_io_status {UNUSED} 
