# ----------------------------------------
# Created on: Wed Sep 20 11:39:52 2023
# Auto generated by Pango
# ----------------------------------------

vsim  -novopt  -L work tb_icmp
add wave *
view wave
view structure
view signals

run 1000ns

# ----------------------------------------
