#Generated by Fabric Compiler ( version 2021.4-SP1.2 <build 96435> ) at Thu Aug 31 17:25:40 2023

dev_map 
dev_map 
dev_map 
dev_map 
dev_map 
dev_map 
dev_map 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
dev_map 
dev_map 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
dev_map 
dev_map 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
dev_map 
dev_map 
dev_map 
dev_map 
dev_map 
dev_map 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
remove_fic -force"C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_lcd_d0/prj/synthesize/ov5640_lcd_syn.fic"
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
remove_design C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/bank/ov5640_lcd/prj/ipcore/pll/pll.idf
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
add_fic "E:/Document/FPGA/PGL/PGL25G/Finalized/ov5640_lcd/prj/synthesize/ov5640_lcd_syn.fic"
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
remove_fic "E:/Document/FPGA/PGL/PGL25G/Finalized/ov5640_lcd/prj/synthesize/ov5640_lcd_syn.fic"
dev_map 
pnr 
report_timing 
gen_bit_stream 
add_fic "E:/Document/FPGA/PGL/PGL25G/Finalized/ov5640_lcd/prj/synthesize/ov5640_lcd_syn.fic"
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
dev_map 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
remove_fic "E:/Document/FPGA/PGL/PGL25G/Finalized/ov5640_lcd/prj/synthesize/ov5640_lcd_syn.fic"
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
add_fic "E:/Document/FPGA/PGL/PGL25G/Finalized/ov5640_lcd/prj/synthesize/ov5640_lcd_syn.fic"
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
remove_fic "E:/Document/FPGA/PGL/PGL25G/Finalized/ov5640_lcd/prj/synthesize/ov5640_lcd_syn.fic"
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
