#Generated by Fabric Compiler ( version 2022.2-SP4.2 <build 132111> ) at Tue Sep 19 14:00:10 2023

add_design "D:/Desktop/7_counter/rtl/counter.v"
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module counter
add_simulation "D:/Desktop/7_counter/sim/tb_counter.v"
add_simulation "D:/Desktop/7_counter/sim/tb_counter.v"
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module counter
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module counter
