# ----------------------------------------
# Created on: Tue Sep 26 09:11:43 2023
# Auto generated by Pango
# ----------------------------------------

vsim  -novopt  -L work tb_key_led
add wave *
view wave
view structure
view signals

run 1000ns

# ----------------------------------------
