# ----------------------------------------
# Created on: Tue Sep 26 09:11:43 2023
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vlog -work work   \
"D:/Desktop/11_key_led/rtl/key_led.v" \
"D:/Desktop/11_key_led/sim/tb/tb_key_led.v" 

# ----------------------------------------
