#Generated by Fabric Compiler ( version 2022.2-SP4.2 <build 132111> ) at Sun Oct  8 15:25:27 2023

add_simulation "E:/Document/FPGA/PGL/PGL25G/Finalized/top_matrix_keyboard/sim/tb_top_matrix_keyboard.v"
