# ----------------------------------------
# Created on: Sat Sep 23 13:12:47 2023
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/usim"
vmap  adc "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/adc"
vmap  ddrc "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/ddrc"
vmap  ddrphy "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/ddrphy"
vmap  hsst_e2 "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/hsst_e2"
vmap  iolhr_dft "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/iolhr_dft"
vmap  ipal_e1 "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/ipal_e1"
vmap  pciegen2 "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/pciegen2"
vlog -work work   \
"E:/PDS/ip_1port_ram/rtl/ip_1port_ram.v" \
"E:/PDS/ip_1port_ram/rtl/ram_rw.v" \
"E:/PDS/ip_1port_ram/prj/ipcore/ram_1port/rtl/ipml_spram_v1_5_ram_1port.v" \
"E:/PDS/ip_1port_ram/prj/ipcore/ram_1port/ram_1port.v" \
"E:/PDS/ip_1port_ram/sim/tb/tb_ip_1port_ram.v" 

# ----------------------------------------
