# ----------------------------------------
# Created on: Tue Sep 19 11:00:43 2023
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vlog -work work   \
"C:/Users/Admin/Desktop/25G/mdio_rw_test/rtl/mdio_ctrl.v" \
"C:/Users/Admin/Desktop/25G/mdio_rw_test/rtl/mdio_dri.v" \
"C:/Users/Admin/Desktop/25G/mdio_rw_test/rtl/mdio_rw_test.v" \
"C:/Users/Admin/Desktop/25G/mdio_rw_test/sim/mdio_slave_interface.v" \
"C:/Users/Admin/Desktop/25G/mdio_rw_test/sim/tb_mdio_rw_test.v" \
"C:/Users/Admin/Desktop/25G/mdio_rw_test/rtl/mdio_ctrl.v" \
"C:/Users/Admin/Desktop/25G/mdio_rw_test/rtl/mdio_dri.v" \
"C:/Users/Admin/Desktop/25G/mdio_rw_test/rtl/mdio_rw_test.v" 

# ----------------------------------------
