# ----------------------------------------
# Created on: Tue Oct 11 16:06:17 2022
# Auto generated by Pango
# ----------------------------------------

vsim  -novopt  -L work -L usim -L adc -L ddrc -L ddrphy -L hsst_e2 -L iolhr_dft -L ipal_e1 -L pciegen2 tb_arp usim.GTP_GRS
add wave *
view wave
view structure
view signals

run 10ms

# ----------------------------------------
