# ----------------------------------------
# Created on: Tue Oct 11 16:06:17 2022
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "F:/modeltech64_10.4/pango_sim_libraries/usim"
vmap  adc "F:/modeltech64_10.4/pango_sim_libraries/adc"
vmap  ddrc "F:/modeltech64_10.4/pango_sim_libraries/ddrc"
vmap  ddrphy "F:/modeltech64_10.4/pango_sim_libraries/ddrphy"
vmap  hsst_e2 "F:/modeltech64_10.4/pango_sim_libraries/hsst_e2"
vmap  iolhr_dft "F:/modeltech64_10.4/pango_sim_libraries/iolhr_dft"
vmap  ipal_e1 "F:/modeltech64_10.4/pango_sim_libraries/ipal_e1"
vmap  pciegen2 "F:/modeltech64_10.4/pango_sim_libraries/pciegen2"
vlog   "C:/Users/ch/Desktop/2022.1/eth_arp_test/rtl/arp_ctrl.v" -work work
vlog   "C:/Users/ch/Desktop/2022.1/eth_arp_test/rtl/arp/arp.v" -work work
vlog   "C:/Users/ch/Desktop/2022.1/eth_arp_test/rtl/arp/arp_rx.v" -work work
vlog   "C:/Users/ch/Desktop/2022.1/eth_arp_test/rtl/arp/arp_tx.v" -work work
vlog   "C:/Users/ch/Desktop/2022.1/eth_arp_test/rtl/arp/crc32_d8.v" -work work
vlog   "C:/Users/ch/Desktop/2022.1/eth_arp_test/rtl/reset_dly.v" -work work
vlog   "C:/Users/ch/Desktop/2022.1/eth_arp_test/rtl/eth_arp_test.v" -work work
vlog   "C:/Users/ch/Desktop/2022.1/eth_arp_test/rtl/gmii_to_rgmii/gmii_to_rgmii.v" -work work
vlog   "C:/Users/ch/Desktop/2022.1/eth_arp_test/rtl/gmii_to_rgmii/rgmii_rx.v" -work work
vlog   "C:/Users/ch/Desktop/2022.1/eth_arp_test/rtl/gmii_to_rgmii/rgmii_tx.v" -work work
vlog   "C:/Users/ch/Desktop/2022.1/eth_arp_test/prj/ipcore/pll_sft/pll_sft.v" -work work
vlog   "C:/Users/ch/Desktop/2022.1/eth_arp_test/sim/tb/tb_arp.v" -work work

# ----------------------------------------
