# ----------------------------------------
# Created on: Mon Oct 16 10:18:06 2023
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/usim"
vmap  adc "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/adc"
vmap  ddrc "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/ddrc"
vmap  ddrphy "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/ddrphy"
vmap  hsst_e2 "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/hsst_e2"
vmap  iolhr_dft "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/iolhr_dft"
vmap  ipal_e1 "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/ipal_e1"
vmap  pciegen2 "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/pciegen2"
vlog -work work   \
"E:/PDS/ip_fifo/rtl/ip_fifo.v" \
"E:/PDS/ip_fifo/rtl/fifo_wr.v" \
"E:/PDS/ip_fifo/rtl/fifo_rd.v" \
"E:/PDS/ip_fifo/prj/ipcore/async_fifo/rtl/ipml_fifo_ctrl_v1_4_async_fifo.v" \
"E:/PDS/ip_fifo/prj/ipcore/async_fifo/rtl/ipml_sdpram_v1_6_async_fifo.v" \
"E:/PDS/ip_fifo/prj/ipcore/async_fifo/rtl/ipml_fifo_v1_7_async_fifo.v" \
"E:/PDS/ip_fifo/prj/ipcore/async_fifo/async_fifo.v" \
"E:/PDS/ip_fifo/prj/ipcore/pll_clk/pll_clk.v" \
"E:/PDS/ip_fifo/sim/tb/tb_ip_fifo.v" 

# ----------------------------------------
