# ----------------------------------------
# Created on: Fri Oct 13 10:17:39 2023
# Auto generated by Pango
# ----------------------------------------

vsim  -novopt  -L work tb_dds
add wave *
view wave
view structure
view signals

run 1000ns

# ----------------------------------------
