# ----------------------------------------
# Created on: Fri Oct 13 10:17:39 2023
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vlog -work work   \
"D:/Desktop/32_dds/rtl/da_wave_send.v" \
"D:/Desktop/32_dds/rtl/dds.v" \
"D:/Desktop/32_dds/rtl/key_debounce.v" \
"D:/Desktop/32_dds/prj/ipcore/pll_clk/pll_clk.v" \
"D:/Desktop/32_dds/prj/ipcore/rom_400x8b/rtl/ipm_distributed_rom_v1_3_rom_400x8b.v" \
"D:/Desktop/32_dds/prj/ipcore/rom_400x8b/rom_400x8b.v" \
"D:/Desktop/32_dds/sim/tb/tb_dds.v" 

# ----------------------------------------
