# ----------------------------------------
# Created on: Wed Sep 20 11:39:51 2023
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vlog -work work   \
"C:/Users/Admin/Desktop/25G/3_eth_icmp_test/rtl/eth_ctrl.v" \
"C:/Users/Admin/Desktop/25G/3_eth_icmp_test/rtl/eth_icmp_test.v" \
"C:/Users/Admin/Desktop/25G/3_eth_icmp_test/rtl/icmp/icmp.v" \
"C:/Users/Admin/Desktop/25G/3_eth_icmp_test/rtl/icmp/icmp_rx.v" \
"C:/Users/Admin/Desktop/25G/3_eth_icmp_test/rtl/icmp/icmp_tx.v" \
"C:/Users/Admin/Desktop/25G/3_eth_icmp_test/rtl/gmii_to_rgmii/gmii_to_rgmii.v" \
"C:/Users/Admin/Desktop/25G/3_eth_icmp_test/rtl/gmii_to_rgmii/rgmii_rx.v" \
"C:/Users/Admin/Desktop/25G/3_eth_icmp_test/rtl/gmii_to_rgmii/rgmii_tx.v" \
"C:/Users/Admin/Desktop/25G/3_eth_icmp_test/rtl/arp/arp.v" \
"C:/Users/Admin/Desktop/25G/3_eth_icmp_test/rtl/arp/arp_rx.v" \
"C:/Users/Admin/Desktop/25G/3_eth_icmp_test/rtl/arp/arp_tx.v" \
"C:/Users/Admin/Desktop/25G/3_eth_icmp_test/rtl/arp/crc32_d8.v" \
"C:/Users/Admin/Desktop/25G/3_eth_icmp_test/prj/ipcore/pll_sft/pll_sft.v" \
"C:/Users/Admin/Desktop/25G/3_eth_icmp_test/prj/ipcore/clk_wiz_0/clk_wiz_0.v" \
"C:/Users/Admin/Desktop/25G/3_eth_icmp_test/prj/ipcore/sync_fifo_2048x8b/rtl/ipml_fifo_ctrl_v1_4_sync_fifo_2048x8b.v" \
"C:/Users/Admin/Desktop/25G/3_eth_icmp_test/prj/ipcore/sync_fifo_2048x8b/rtl/ipml_sdpram_v1_6_sync_fifo_2048x8b.v" \
"C:/Users/Admin/Desktop/25G/3_eth_icmp_test/prj/ipcore/sync_fifo_2048x8b/rtl/ipml_fifo_v1_7_sync_fifo_2048x8b.v" \
"C:/Users/Admin/Desktop/25G/3_eth_icmp_test/prj/ipcore/sync_fifo_2048x8b/sync_fifo_2048x8b.v" \
"C:/Users/Admin/Desktop/25G/3_eth_icmp_test/sim/tb_icmp.v" \
"C:/Users/Admin/Desktop/25G/3_eth_icmp_test/rtl/icmp/icmp.v" \
"C:/Users/Admin/Desktop/25G/3_eth_icmp_test/rtl/icmp/icmp_rx.v" \
"C:/Users/Admin/Desktop/25G/3_eth_icmp_test/rtl/icmp/icmp_tx.v" \
"C:/Users/Admin/Desktop/25G/3_eth_icmp_test/rtl/arp/crc32_d8.v" 

# ----------------------------------------
