#Generated by Fabric Compiler ( version 2022.2-SP4.2 <build 132111> ) at Mon Sep 18 15:29:44 2023

add_design "D:/Desktop/4_decoder3_8/rtl/decoder3_8.v"
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module decoder3_8
add_simulation "D:/Desktop/4_decoder3_8/rtl/decoder3_8.v"
remove_simulation "D:/Desktop/4_decoder3_8/rtl/decoder3_8.v"
add_simulation "D:/Desktop/4_decoder3_8/sim/tb_decoder_3_8.v"
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module decoder3_8
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module decoder3_8
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module decoder3_8
