#Generated by Fabric Compiler ( version 2021.4-SP1.2 <build 96435> ) at Thu Aug 31 17:25:40 2023

dev_map 
dev_map 
dev_map 
dev_map 
dev_map 
dev_map 
dev_map 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
dev_map 
dev_map 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
dev_map 
dev_map 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
dev_map 
dev_map 
dev_map 
dev_map 
dev_map 
dev_map 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
remove_fic -force"C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/ov5640_lcd_d0/prj/synthesize/ov5640_lcd_syn.fic"
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
remove_design C:/Users/ALIENTEK/Desktop/licheng/Test/Ziguang/PGL25G/bank/ov5640_lcd/prj/ipcore/pll/pll.idf
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
add_fic "E:/Document/FPGA/PGL/PGL25G/Finalized/ov5640_lcd/prj/synthesize/ov5640_lcd_syn.fic"
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
remove_fic "E:/Document/FPGA/PGL/PGL25G/Finalized/ov5640_lcd/prj/synthesize/ov5640_lcd_syn.fic"
dev_map 
pnr 
report_timing 
gen_bit_stream 
add_fic "E:/Document/FPGA/PGL/PGL25G/Finalized/ov5640_lcd/prj/synthesize/ov5640_lcd_syn.fic"
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
dev_map 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
remove_fic "E:/Document/FPGA/PGL/PGL25G/Finalized/ov5640_lcd/prj/synthesize/ov5640_lcd_syn.fic"
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
add_fic "E:/Document/FPGA/PGL/PGL25G/Finalized/ov5640_lcd/prj/synthesize/ov5640_lcd_syn.fic"
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
remove_fic "E:/Document/FPGA/PGL/PGL25G/Finalized/ov5640_lcd/prj/synthesize/ov5640_lcd_syn.fic"
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_lcd
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
remove_design -force -verilog "D:/Desktop/ov5640_lcd/rtl/ov5640_lcd.v"
remove_design -force -verilog "D:/Desktop/ov5640_lcd/rtl/picture_size.v"
remove_design -force -verilog "D:/Desktop/ov5640_lcd/rtl/lcd_rgb_top/clk_div.v"
remove_design -force -verilog "D:/Desktop/ov5640_lcd/rtl/lcd_rgb_top/lcd_driver.v"
remove_design -force -verilog "D:/Desktop/ov5640_lcd/rtl/lcd_rgb_top/rd_id.v"
remove_design -force -verilog "D:/Desktop/ov5640_lcd/rtl/lcd_rgb_top/lcd_rgb_top.v"
remove_constraint -force -logic -fdc "D:/Desktop/ov5640_hdmi_yuv/prj/source/ov5640_lcd_pin.fdc"
add_design "D:/Desktop/ov5640_hdmi_yuv/rtl/vip/vip.v"
add_design "D:/Desktop/ov5640_hdmi_yuv/rtl/vip/rgb2ycbcr.v"
add_design "D:/Desktop/ov5640_hdmi_yuv/rtl/hdmi_top/asyn_rst_syn.v"
add_design "D:/Desktop/ov5640_hdmi_yuv/rtl/hdmi_top/dvi_encoder.v"
add_design "D:/Desktop/ov5640_hdmi_yuv/rtl/hdmi_top/dvi_transmitter_top.v"
add_design "D:/Desktop/ov5640_hdmi_yuv/rtl/hdmi_top/hdmi_top.v"
add_design "D:/Desktop/ov5640_hdmi_yuv/rtl/hdmi_top/serializer_10_to_1.v"
add_design "D:/Desktop/ov5640_hdmi_yuv/rtl/hdmi_top/video_driver.v"
add_design "D:/Desktop/ov5640_hdmi_yuv/rtl/ov5640_hdmi_yuv.v"
add_design D:/Desktop/ov5640_hdmi_yuv/prj/ipcore/pll_clk/pll_clk.idf
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_yuv
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
add_constraint "D:/Desktop/ov5640_hdmi_yuv/prj/source/ov5640_hdmi_yuv.fdc"
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
remove_design -force D:/Desktop/ov5640_hdmi_yuv/prj/ipcore/ddr3_ip/ddr3_ip.idf
add_design D:/Desktop/ov5640_hdmi_yuv/prj/ipcore/ddr3_ip/ddr3_ip.idf
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_yuv
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_yuv
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_yuv
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
remove_design -verilog "D:/Desktop/ov5640_hdmi_yuv/rtl/ov5640_hdmi_yuv.v"
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module ov5640_dri
synthesize -dir {} -ads -selected_syn_tool_opt 2 
add_design "D:/Desktop/ov5640_hdmi_yuv/rtl/ov5640_hdmi_yuv.v"
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module ov5640_dri
synthesize -dir {} -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_yuv
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_global_include D:/Desktop/ov5640_hdmi_yuv/rtl/ov5640_hdmi_yuv.v true
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_yuv
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_global_include D:/Desktop/ov5640_hdmi_yuv/rtl/ov5640_hdmi_yuv.v false
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_yuv
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_yuv
synthesize -dir {} -ads -selected_syn_tool_opt 2 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_yuv
synthesize -dir {} -ads -selected_syn_tool_opt 2 
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_yuv
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_yuv
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
remove_design -force D:/Desktop/ov5640_hdmi_yuv/prj/ipcore/ddr3_ip/ddr3_ip.idf
add_design D:/Desktop/ov5640_hdmi_yuv/prj/ipcore/ddr3_ip/ddr3_ip.idf
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_yuv
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_yuv
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_yuv
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_yuv
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_yuv
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_yuv
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/vip/line_shift_ram_8bit.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/vip/median_filter_3x3.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/vip/sort3.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/vip/vip_matrix_generate_3x3_8bit.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/vip/vip_gray_median_filter.v"
add_design D:/Desktop/25G/ov5640_hdmi_median_filter/prj/ipcore/blk_mem_gen_0/blk_mem_gen_0.idf
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/ov5640_dri/cmos_capture_data.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/ov5640_dri/i2c_dri.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/ov5640_dri/i2c_ov5640_rgb565_cfg.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/ov5640_dri/ov5640_dri.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/ddr3_ctrl_top/aq_axi_master.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/ddr3_ctrl_top/ctrl_fifo.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/ddr3_ctrl_top/ddr3_ctrl_top.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/ddr3_ctrl_top/ddr3_rw_ctrl.v"
remove_design -force -verilog "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/rtl/ov5640_dri/cmos_capture_data.v"
remove_design -force -verilog "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/rtl/ov5640_dri/i2c_dri.v"
remove_design -force -verilog "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/rtl/ov5640_dri/i2c_ov5640_rgb565_cfg.v"
remove_design -force -verilog "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/rtl/ddr3_ctrl_top/aq_axi_master.v"
remove_design -force -verilog "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/rtl/ddr3_ctrl_top/ctrl_fifo.v"
remove_design -force -verilog "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/rtl/ddr3_ctrl_top/ddr3_rw_ctrl.v"
remove_design -force -verilog "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/rtl/ddr3_ctrl_top/ddr3_ctrl_top.v"
remove_design -force -verilog "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/rtl/ov5640_dri/ov5640_dri.v"
remove_constraint  -logic -fdc "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/source/ov5640_hdmi_yuv.fdc"
remove_design -force -verilog "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/rtl/vip/vip.v"
remove_design -force -verilog "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/rtl/vip/rgb2ycbcr.v"
remove_design -force -verilog "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/rtl/hdmi_top/asyn_rst_syn.v"
remove_design -force -verilog "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/rtl/hdmi_top/dvi_encoder.v"
remove_design -force -verilog "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/rtl/hdmi_top/dvi_transmitter_top.v"
remove_design -force -verilog "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/rtl/hdmi_top/hdmi_top.v"
remove_design -force -verilog "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/rtl/hdmi_top/serializer_10_to_1.v"
remove_design -force -verilog "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/rtl/hdmi_top/video_driver.v"
remove_design -force -verilog "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/rtl/ov5640_hdmi_yuv.v"
remove_design -force -verilog "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/rtl/vip/line_shift_ram_8bit.v"
remove_design -force -verilog "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/rtl/vip/median_filter_3x3.v"
remove_design -force -verilog "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/rtl/vip/sort3.v"
remove_design -force -verilog "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/rtl/vip/vip_matrix_generate_3x3_8bit.v"
remove_design -force -verilog "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/rtl/vip/vip_gray_median_filter.v"
remove_design -force -verilog "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/rtl/ov5640_dri/cmos_capture_data.v"
remove_design -force -verilog "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/rtl/ov5640_dri/i2c_dri.v"
remove_design -force -verilog "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/rtl/ov5640_dri/i2c_ov5640_rgb565_cfg.v"
remove_design -force -verilog "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/rtl/ov5640_dri/ov5640_dri.v"
remove_design -force -verilog "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/rtl/ddr3_ctrl_top/aq_axi_master.v"
remove_design -force -verilog "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/rtl/ddr3_ctrl_top/ctrl_fifo.v"
remove_design -force -verilog "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/rtl/ddr3_ctrl_top/ddr3_ctrl_top.v"
remove_design -force -verilog "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/rtl/ddr3_ctrl_top/ddr3_rw_ctrl.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/ddr3_ctrl_top/aq_axi_master.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/ddr3_ctrl_top/ctrl_fifo.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/ddr3_ctrl_top/ddr3_ctrl_top.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/ddr3_ctrl_top/ddr3_rw_ctrl.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/hdmi_top/asyn_rst_syn.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/hdmi_top/dvi_encoder.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/hdmi_top/dvi_transmitter_top.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/hdmi_top/hdmi_top.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/hdmi_top/serializer_10_to_1.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/hdmi_top/video_driver.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/ov5640_dri/cmos_capture_data.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/ov5640_dri/i2c_dri.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/ov5640_dri/i2c_ov5640_rgb565_cfg.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/ov5640_dri/ov5640_dri.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/vip/line_shift_ram_8bit.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/vip/median_filter_3x3.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/vip/rgb2ycbcr.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/vip/sort3.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/vip/vip.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/vip/vip_gray_median_filter.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/vip/vip_matrix_generate_3x3_8bit.v"
add_design "D:/Desktop/25G/ov5640_hdmi_median_filter/rtl/ov5640_hdmi_median_filter.v"
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_median_filter
add_constraint "D:/Desktop/25G/ov5640_hdmi_median_filter/prj/source/ov5640_hdmi_median_filter.fdc"
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_median_filter
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_median_filter
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_median_filter
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
remove_design -force D:/Desktop/50G/ov5640_hdmi_median_filter/prj/ipcore/ddr3_ip/ddr3_ip.idf
add_design D:/Desktop/50G/ov5640_hdmi_median_filter/prj/ipcore/ddr3_ip/ddr3_ip.idf
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_median_filter
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_median_filter
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_median_filter
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_median_filter
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_median_filter
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
add_design "D:/Desktop/50G/ov5640_hdmi_img_binarization/rtl/vip/binarization.v"
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_median_filter
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_median_filter
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
remove_design -force -verilog "D:/Desktop/50G/ov5640_hdmi_img_binarization/prj/rtl/ddr3_ctrl_top/aq_axi_master.v"
remove_design -force -verilog "D:/Desktop/50G/ov5640_hdmi_img_binarization/prj/rtl/ddr3_ctrl_top/ctrl_fifo.v"
remove_design -force -verilog "D:/Desktop/50G/ov5640_hdmi_img_binarization/prj/rtl/ddr3_ctrl_top/ddr3_ctrl_top.v"
remove_design -force -verilog "D:/Desktop/50G/ov5640_hdmi_img_binarization/prj/rtl/ddr3_ctrl_top/ddr3_rw_ctrl.v"
remove_design -force -verilog "D:/Desktop/50G/ov5640_hdmi_img_binarization/prj/rtl/hdmi_top/asyn_rst_syn.v"
remove_design -force -verilog "D:/Desktop/50G/ov5640_hdmi_img_binarization/prj/rtl/hdmi_top/dvi_encoder.v"
remove_design -force -verilog "D:/Desktop/50G/ov5640_hdmi_img_binarization/prj/rtl/hdmi_top/dvi_transmitter_top.v"
remove_design -force -verilog "D:/Desktop/50G/ov5640_hdmi_img_binarization/prj/rtl/hdmi_top/hdmi_top.v"
remove_design -force -verilog "D:/Desktop/50G/ov5640_hdmi_img_binarization/prj/rtl/hdmi_top/serializer_10_to_1.v"
remove_design -force -verilog "D:/Desktop/50G/ov5640_hdmi_img_binarization/prj/rtl/hdmi_top/video_driver.v"
remove_design -force -verilog "D:/Desktop/50G/ov5640_hdmi_img_binarization/prj/rtl/ov5640_dri/cmos_capture_data.v"
remove_design -force -verilog "D:/Desktop/50G/ov5640_hdmi_img_binarization/prj/rtl/ov5640_dri/i2c_dri.v"
remove_design -force -verilog "D:/Desktop/50G/ov5640_hdmi_img_binarization/prj/rtl/ov5640_dri/i2c_ov5640_rgb565_cfg.v"
remove_design -force -verilog "D:/Desktop/50G/ov5640_hdmi_img_binarization/prj/rtl/ov5640_dri/ov5640_dri.v"
remove_design -force -verilog "D:/Desktop/50G/ov5640_hdmi_img_binarization/prj/rtl/vip/line_shift_ram_8bit.v"
remove_design -force -verilog "D:/Desktop/50G/ov5640_hdmi_img_binarization/prj/rtl/vip/median_filter_3x3.v"
remove_design -force -verilog "D:/Desktop/50G/ov5640_hdmi_img_binarization/prj/rtl/vip/rgb2ycbcr.v"
remove_design -force -verilog "D:/Desktop/50G/ov5640_hdmi_img_binarization/prj/rtl/vip/sort3.v"
remove_design -force -verilog "D:/Desktop/50G/ov5640_hdmi_img_binarization/prj/rtl/vip/vip.v"
remove_design -force -verilog "D:/Desktop/50G/ov5640_hdmi_img_binarization/prj/rtl/vip/vip_gray_median_filter.v"
remove_design -force -verilog "D:/Desktop/50G/ov5640_hdmi_img_binarization/prj/rtl/vip/vip_matrix_generate_3x3_8bit.v"
remove_design -force -verilog "D:/Desktop/50G/ov5640_hdmi_img_binarization/prj/rtl/ov5640_hdmi_median_filter.v"
remove_design -force -verilog "D:/Desktop/50G/ov5640_hdmi_img_binarization/prj/rtl/vip/binarization.v"
add_design "D:/Desktop/50G/ov5640_hdmi_img_binarization/rtl/ddr3_ctrl_top/aq_axi_master.v"
add_design "D:/Desktop/50G/ov5640_hdmi_img_binarization/rtl/ddr3_ctrl_top/ctrl_fifo.v"
add_design "D:/Desktop/50G/ov5640_hdmi_img_binarization/rtl/ddr3_ctrl_top/ddr3_ctrl_top.v"
add_design "D:/Desktop/50G/ov5640_hdmi_img_binarization/rtl/ddr3_ctrl_top/ddr3_rw_ctrl.v"
add_design "D:/Desktop/50G/ov5640_hdmi_img_binarization/rtl/hdmi_top/video_driver.v"
add_design "D:/Desktop/50G/ov5640_hdmi_img_binarization/rtl/hdmi_top/serializer_10_to_1.v"
add_design "D:/Desktop/50G/ov5640_hdmi_img_binarization/rtl/hdmi_top/hdmi_top.v"
add_design "D:/Desktop/50G/ov5640_hdmi_img_binarization/rtl/hdmi_top/dvi_transmitter_top.v"
add_design "D:/Desktop/50G/ov5640_hdmi_img_binarization/rtl/hdmi_top/dvi_encoder.v"
add_design "D:/Desktop/50G/ov5640_hdmi_img_binarization/rtl/hdmi_top/asyn_rst_syn.v"
add_design "D:/Desktop/50G/ov5640_hdmi_img_binarization/rtl/ov5640_dri/cmos_capture_data.v"
add_design "D:/Desktop/50G/ov5640_hdmi_img_binarization/rtl/ov5640_dri/i2c_dri.v"
add_design "D:/Desktop/50G/ov5640_hdmi_img_binarization/rtl/ov5640_dri/i2c_ov5640_rgb565_cfg.v"
add_design "D:/Desktop/50G/ov5640_hdmi_img_binarization/rtl/ov5640_dri/ov5640_dri.v"
add_design "D:/Desktop/50G/ov5640_hdmi_img_binarization/rtl/vip/binarization.v"
add_design "D:/Desktop/50G/ov5640_hdmi_img_binarization/rtl/vip/line_shift_ram_8bit.v"
add_design "D:/Desktop/50G/ov5640_hdmi_img_binarization/rtl/vip/median_filter_3x3.v"
add_design "D:/Desktop/50G/ov5640_hdmi_img_binarization/rtl/vip/rgb2ycbcr.v"
add_design "D:/Desktop/50G/ov5640_hdmi_img_binarization/rtl/vip/sort3.v"
add_design "D:/Desktop/50G/ov5640_hdmi_img_binarization/rtl/vip/vip.v"
add_design "D:/Desktop/50G/ov5640_hdmi_img_binarization/rtl/vip/vip_gray_median_filter.v"
add_design "D:/Desktop/50G/ov5640_hdmi_img_binarization/rtl/vip/vip_matrix_generate_3x3_8bit.v"
add_design "D:/Desktop/50G/ov5640_hdmi_img_binarization/rtl/ov5640_hdmi_img_binarization.v"
remove_constraint  -logic -fdc "D:/Desktop/50G/ov5640_hdmi_img_binarization/prj/source/ov5640_hdmi_median_filter.fdc"
add_constraint "D:/Desktop/50G/ov5640_hdmi_img_binarization/prj/source/ov5640_hdmi_img_binarization.fdc"
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_img_binarization
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
remove_design -force D:/Desktop/25G/ov5640_hdmi_img_binarization/prj/ipcore/ddr3_ip/ddr3_ip.idf
add_design D:/Desktop/25G/ov5640_hdmi_img_binarization/prj/ipcore/ddr3_ip/ddr3_ip.idf
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_img_binarization
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_img_binarization
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module ov5640_hdmi_img_binarization
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
