# ----------------------------------------
# Created on: Tue Sep 26 14:57:30 2023
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/usim"
vmap  adc "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/adc"
vmap  ddrc "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/ddrc"
vmap  ddrphy "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/ddrphy"
vmap  hsst_e2 "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/hsst_e2"
vmap  iolhr_dft "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/iolhr_dft"
vmap  ipal_e1 "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/ipal_e1"
vmap  pciegen2 "D:/modeltech64_2020.4/PDS2020.2_sp4.2_lib/pciegen2"
vlog -work work   \
"E:/PDS/ip_2port_ram/rtl/ip_2port_ram.v" \
"E:/PDS/ip_2port_ram/rtl/ram_wr.v" \
"E:/PDS/ip_2port_ram/rtl/ram_rd.v" \
"E:/PDS/ip_2port_ram/prj/ipcore/ram_2port/rtl/ipml_sdpram_v1_6_ram_2port.v" \
"E:/PDS/ip_2port_ram/prj/ipcore/ram_2port/ram_2port.v" \
"E:/PDS/ip_2port_ram/sim/tb/tb_ip_2port_ram.v" 

# ----------------------------------------
