# ----------------------------------------
# Created on: Sun Oct  8 17:29:32 2023
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "D:/modeltech64_2020.4/PDS_sim_lib/PDS_2022.2-SP4.2-ads/usim"
vmap  adc "D:/modeltech64_2020.4/PDS_sim_lib/PDS_2022.2-SP4.2-ads/adc"
vmap  ddrc "D:/modeltech64_2020.4/PDS_sim_lib/PDS_2022.2-SP4.2-ads/ddrc"
vmap  ddrphy "D:/modeltech64_2020.4/PDS_sim_lib/PDS_2022.2-SP4.2-ads/ddrphy"
vmap  hsst_e2 "D:/modeltech64_2020.4/PDS_sim_lib/PDS_2022.2-SP4.2-ads/hsst_e2"
vmap  iolhr_dft "D:/modeltech64_2020.4/PDS_sim_lib/PDS_2022.2-SP4.2-ads/iolhr_dft"
vmap  ipal_e1 "D:/modeltech64_2020.4/PDS_sim_lib/PDS_2022.2-SP4.2-ads/ipal_e1"
vmap  pciegen2 "D:/modeltech64_2020.4/PDS_sim_lib/PDS_2022.2-SP4.2-ads/pciegen2"
vlog -work work   \
"E:/Document/FPGA/PGL/PGL25G/Finalized/lcd_rgb_char/rtl/clk_div.v" \
"E:/Document/FPGA/PGL/PGL25G/Finalized/lcd_rgb_char/rtl/lcd_display.v" \
"E:/Document/FPGA/PGL/PGL25G/Finalized/lcd_rgb_char/rtl/lcd_driver.v" \
"E:/Document/FPGA/PGL/PGL25G/Finalized/lcd_rgb_char/rtl/lcd_rgb_char.v" \
"E:/Document/FPGA/PGL/PGL25G/Finalized/lcd_rgb_char/rtl/rd_id.v" \
"E:/Document/FPGA/PGL/PGL25G/Finalized/lcd_rgb_char/prj/ipcore/blk_mem_gen_0/rtl/ipml_rom_v1_5_blk_mem_gen_0.v" \
"E:/Document/FPGA/PGL/PGL25G/Finalized/lcd_rgb_char/prj/ipcore/blk_mem_gen_0/rtl/ipml_spram_v1_5_blk_mem_gen_0.v" \
"E:/Document/FPGA/PGL/PGL25G/Finalized/lcd_rgb_char/prj/ipcore/blk_mem_gen_0/blk_mem_gen_0.v" \
"E:/Document/FPGA/PGL/PGL25G/Finalized/lcd_rgb_char/sim/tb_lcd_rgb_char.v" 

# ----------------------------------------
