# ----------------------------------------
# Created on: Sun Oct  8 13:55:50 2023
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "D:/modeltech64_2020.4/pango/PDS22SP4/usim"
vmap  adc "D:/modeltech64_2020.4/pango/PDS22SP4/adc"
vmap  ddrc "D:/modeltech64_2020.4/pango/PDS22SP4/ddrc"
vmap  ddrphy "D:/modeltech64_2020.4/pango/PDS22SP4/ddrphy"
vmap  hsst_e2 "D:/modeltech64_2020.4/pango/PDS22SP4/hsst_e2"
vmap  iolhr_dft "D:/modeltech64_2020.4/pango/PDS22SP4/iolhr_dft"
vmap  ipal_e1 "D:/modeltech64_2020.4/pango/PDS22SP4/ipal_e1"
vmap  pciegen2 "D:/modeltech64_2020.4/pango/PDS22SP4/pciegen2"
vlog -work work   \
"E:/Document/FPGA/PGL/PGL50G/Test program/hdmi_block_move/rtl/asyn_rst_syn.v" \
"E:/Document/FPGA/PGL/PGL50G/Test program/hdmi_block_move/rtl/dvi_encoder.v" \
"E:/Document/FPGA/PGL/PGL50G/Test program/hdmi_block_move/rtl/dvi_transmitter_top.v" \
"E:/Document/FPGA/PGL/PGL50G/Test program/hdmi_block_move/rtl/serializer_10_to_1.v" \
"E:/Document/FPGA/PGL/PGL50G/Test program/hdmi_block_move/rtl/top_hdmi_block_move.v" \
"E:/Document/FPGA/PGL/PGL50G/Test program/hdmi_block_move/rtl/video_display.v" \
"E:/Document/FPGA/PGL/PGL50G/Test program/hdmi_block_move/rtl/video_driver.v" \
"E:/Document/FPGA/PGL/PGL50G/Test program/hdmi_block_move/prj/ipcore/clk_wiz_0/clk_wiz_0.v" \
"E:/Document/FPGA/PGL/PGL50G/Test program/hdmi_block_move/sim/tb_top_hdmi_block_move.v" 

# ----------------------------------------
