#Generated by Fabric Compiler ( version 2022.2-SP4.2 <build 132111> ) at Fri Oct  6 18:26:28 2023

set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module hdmi_colorbar_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module hdmi_colorbar_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module hdmi_colorbar_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module hdmi_colorbar_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module hdmi_colorbar_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module hdmi_colorbar_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module hdmi_colorbar_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
add_simulation "E:/Document/FPGA/PGL/PGL50G/Test program/hdmi_colorbar/sim/tb_hdmi_colorbar_top.v"
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module hdmi_colorbar_top
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50G -speedgrade -6 -package MBG324
compile -top_module hdmi_colorbar_top
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module hdmi_colorbar_top
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL25G -speedgrade -6 -package MBG324
compile -top_module hdmi_colorbar_top
synthesize -dir {} -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
