# ----------------------------------------
# Created on: Sun Oct  8 15:28:07 2023
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "D:/modeltech64_2020.4/pango/PDS22SP4/usim"
vmap  adc "D:/modeltech64_2020.4/pango/PDS22SP4/adc"
vmap  ddrc "D:/modeltech64_2020.4/pango/PDS22SP4/ddrc"
vmap  ddrphy "D:/modeltech64_2020.4/pango/PDS22SP4/ddrphy"
vmap  hsst_e2 "D:/modeltech64_2020.4/pango/PDS22SP4/hsst_e2"
vmap  iolhr_dft "D:/modeltech64_2020.4/pango/PDS22SP4/iolhr_dft"
vmap  ipal_e1 "D:/modeltech64_2020.4/pango/PDS22SP4/ipal_e1"
vmap  pciegen2 "D:/modeltech64_2020.4/pango/PDS22SP4/pciegen2"
vlog -work work   \
"E:/Document/FPGA/PGL/PGL25G/Finalized/top_traffic/rtl/binary2bcd.v" \
"E:/Document/FPGA/PGL/PGL25G/Finalized/top_traffic/rtl/led_ctrl.v" \
"E:/Document/FPGA/PGL/PGL25G/Finalized/top_traffic/rtl/seg_led.v" \
"E:/Document/FPGA/PGL/PGL25G/Finalized/top_traffic/rtl/top_traffic.v" \
"E:/Document/FPGA/PGL/PGL25G/Finalized/top_traffic/rtl/traffic_light_ctrl.v" \
"E:/Document/FPGA/PGL/PGL25G/Finalized/top_traffic/sim/tb_top_traffic.v" 

# ----------------------------------------
